services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python calculate.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync:   true
